services:
  - type: web
    name: norwegian-singles-strava
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: STRAVA_CLIENT_ID
        sync: false
      - key: STRAVA_CLIENT_SECRET
        sync: false
